[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = true
theme = "transparent"
times_to_run = 1
opacity = 0.9
storymode = true
storymodemethod = 1
storymode_max_length = 5000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0
channel_name = ""

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.05
enable_extra_audio = false
background_thumbnail = true
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "elevenlabs"
random_voice = false
elevenlabs_voice_name = "Brian"
elevenlabs_api_key = ""
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = ""
client_secret = ""
username = ""
password = ""
2fa = false

[reddit.thread]
random = true
subreddit = "AmItheAsshole+relationship_advice+confession+tifu"
post_id = ""
max_comment_length = 500
min_comment_length = 20
post_lang = ""
min_comments = 20
